version: '3.8'

services:
  db-container:
    image: postgres:latest
    container_name: soundtracker_database
    restart: always
    networks:
      - movies-network
    environment:
        POSTGRES_USER: dbmsuser
        POSTGRES_PASSWORD: 191688
        POSTGRES_DB: movieservicebd
    volumes:
      - /home/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    image: kelbri/soundtracker_backend:0.0.1
    container_name: soundtracker_backend
    restart: always
    networks:
      - movies-network
    depends_on:
      - db-container
    ports:
      - "8080:8080"
  frontend:
    build: ./angular-client
    image: kelbri/soundtracker_frontend:0.0.1
    container_name: soundtracker_frontend
    restart: always
    networks:
      - movies-network
    ports:
      - "8888:4200"
networks:
  movies-network:
    driver: bridge
